[ScanPath]
class_name = "Circle"

[ScanPath.kwargs]
center_x = 375
center_y = 375
z = 0
tilt = 0
radius = 375
n_points = 20

[Scan.scanner.camera]
module = "plantimager.urlcam"

[Scan.scanner.camera.kwargs]
url = "http://192.168.0.1:8080"

[Scan.scanner.gimbal]
module = "plantimager.blgimbal"

[Scan.scanner.gimbal.kwargs]
port = "/dev/ttyACM1"
has_tilt = false
zero_pan = 0
invert_rotation = true

[Scan.scanner.cnc]
module = "plantimager.grbl"

[Scan.scanner.cnc.kwargs]
port = "/dev/ttyACM0"
baud_rate = 115200
homing = true

[Scan.metadata.workspace]
x = [50, 800, ]
y = [50, 800, ]
z = [-100, 300, ]