[ScanPath]
class_name = "Circle"

[ScanPath.kwargs]
center_x = -350
center_y = -350
z = 0
tilt = 0
radius = 300
n_points = 6

[Scan.scanner.camera]
module = "romiscanner.urlcam"

[Scan.scanner.cnc]
module = "romiscanner.grbl"

[Scan.scanner.gimbal]
module = "romiscanner.blgimbal"

[Scan.scanner.camera.kwargs]
url = "http://192.168.0.1:8080"

[Scan.scanner.cnc.kwargs]
homing = true
port = "/dev/ttyACM0"

[Scan.scanner.gimbal.kwargs]
port = "/dev/ttyACM1"
has_tilt = false
zero_pan = 180
invert_rotation = true

[Scan.metadata.workspace]
x = [ 200, 600,]
y = [ 200, 600,]
z = [ -100, 300,]