[VirtualPlant]
lpy_file_id = "arabidopsis_notex"

[VirtualPlant.lpy_globals]
BRANCHON = false
MEAN_NB_DAYS = 40
STDEV_NB_DAYS = 5
BETA = 51
INTERNODE_LENGTH = 1.3
STEM_DIAMETER = 0.25

[PaletteFileset]
scan_id = "vscan_data"

[HdriFileset]
scan_id = "vscan_data"

[LpyFileset]
scan_id = "vscan_data"

[ScanPath.kwargs]
center_x = 0
center_y = 0
z = 32
tilt = 3
radius = 40
n_points = 36

[ScanPath]
class_name = "Circle"

[VirtualScan]
load_scene = false
scene_file_id = ""
use_palette = true
use_hdri = true
obj_fileset = "VirtualPlant"
hdri_fileset = "HdriFileset"
scene_fileset = "SceneFileset"
palette_fileset = "PaletteFileset"
render_ground_truth = true
colorize = true

[VirtualScan.scanner]
width = 1440
height = 1080
focal = 16
flash = false
port = 9001
add_leaf_displacement = true
