[ObjFileset]
scan_id = "vscan_data"

[PaletteFileset]
scan_id = "vscan_data"

[HdriFileset]
scan_id = "vscan_data"

[LpyFileset]
scan_id = "vscan_data"

[SceneFileset]
scan_id = "vscan_data"

[ScanPath]
class_name = "Circle"

[VirtualScan]
obj_fileset = "VirtualPlant"
use_palette = true
use_hdri = true
load_scene = false
scene_file_id = "pot"
render_ground_truth = true

[VirtualPlant]
lpy_file_id = "arabidopsis_notex"

[Voxels]
type = "averaging"
voxel_size = 0.05

[ScanPath.kwargs]
center_x = -2
center_y = 3
z = 65
tilt = 8
radius = 75
n_points = 36

[VirtualScan.scanner]
width = 896
height = 896
focal = 29
flash = true
add_leaf_displacement = true

[VirtualPlant.lpy_globals]
BRANCHON = false
MEAN_NB_DAYS = 70
STDEV_NB_DAYS = 5
BETA = 51
INTERNODE_LENGTH = 1.3
STEM_DIAMETER = 0.09
