[ObjFileset]
scan_id = "vscan_data"

[PaletteFileset]
scan_id = "vscan_data"

[HdriFileset]
scan_id = "vscan_data"

[LpyFileset]
scan_id = "vscan_data"

[SceneFileset]
scan_id = "vscan_data"

[VirtualPlant]
lpy_file_id = "arabidopsis_notex"

[VirtualPlant.lpy_globals]
BRANCHON = false
MEAN_NB_DAYS = 50
STDEV_NB_DAYS = 5
BETA = 51
INTERNODE_LENGTH = 1.3
STEM_DIAMETER = 0.15

[ScanPath.kwargs]
center_x = 0
center_y = 0
z = 32
tilt = 3
radius = 40
n_points = 36

[ScanPath]
class_name = "Circle"

[VirtualScan]
obj_fileset = "VirtualPlant"
use_palette = true
use_hdri = true
load_scene = false
scene_file_id = "pot"
render_ground_truth = true

[VirtualScan.scanner]
width = 1440
height = 1080
focal = 16
flash = false
add_leaf_displacement = true
port = 9001
