[ObjFileset]
scan_id = "vscan_data"

[HdriFileset]
scan_id = "vscan_data"

[LpyFileset]
scan_id = "vscan_data"

[ScanPath]
class_name = "Circle"

[ScanPath.kwargs]
center_x = 0
center_y = 0
z = 0
tilt = 0
radius = 35
n_points = 16

[VirtualScan]
obj_fileset = "ObjFileset"

[VirtualScan.scanner]
width = 896
height = 896
focal = 24

[VirtualPlant]
lpy_file_id = "arabidopsis_notex"
seed = 123
